### ISSUE TITLE
Horizontal coverage does not allow decimals

### ISSUE THREAD

**Issue by TinyBabyOwl** [flyingpie/windows-terminal-quake#100]
`How much horizontal space the terminal should use. When this is below 100, the terminal is centered. 
This can also be above 100, which can be useful to compensate for the window not always taking a 100% of the screen width,
due to the terminal being bound to column widths (eg. try 100.5 or 101).`

The comment suggests you can use `100.5`, but I get this error when I use that value: 
![image](https://user-images.githubusercontent.com/40748227/137246359-95bde427-b074-408f-b1c5-11e701869ecf.png)

**Comment by flyingpie** [comment]
@TinyBabyOwl Thank you for reaching out! Could you tell me what version you're using? Also, if you're not already, could you try version 1.3 under "releases"?

**Comment by tdy** [comment]
@flyingpie as a side note, 1.3 is still marked as `pre-release` instead of `latest` -- is this intended?

**Comment by flyingpie** [comment]
@tdy I've been sitting on 1.3 for a bit too long, since there's a feature in there that's quite impactful (supporting terminals other than windows terminal). I've pushed that to 1.4 and am finishing up 1.3 currently.

You're right in bringing it up, since it causes some confusion and bug reports of bugs that were already fixed.
