### ISSUE TITLE
Package/Release on winget

### ISSUE THREAD

**Issue by juventus18** [flyingpie/windows-terminal-quake#107]
Would be great if we can get install option thru winget. Thanks!

**Comment by jasonmpotter** [comment]
Seconded ;)

**Comment by flyingpie** [comment]
@juventus18 @jasonmpotter 

Package manifest is underway in PR https://github.com/microsoft/winget-pkgs/pull/124182

Though I'm not entirely happy with the current version yet, as WinGet doesn't have an option (yet) for adding shortcuts to portable apps. So the current version adds a command, which is slightly less convenient than what Scoop does.

**Comment by ShayBox** [comment]
Why not add an installer? It's fairly easy with the "Advanced Installer" Visual Studio extension.  
It would let you add the shortcut, and portable winget apps aren't a great experience right now, they aren't registered as installed apps and can't be uninstalled normally (only via winget uninstall), and since it doesn't support additional tracked files, it wouldn't delete the settings file or other files like an installer/uninstaller would.

**Comment by flyingpie** [comment]
@ShayBox Thank you for commenting!

I've been pondering it due to exactly the points you bring up. It's due to my preference for light-weight apps that don't leave any traces or drop files somewhere obscure.

But I also agree with what you're saying, so I've been looking at some options.

Regarding additional tracked files, I'd like to not have those in the first place. I'm aiming to keep all versions a single-file-exe. Aside from that, there's the settings file, which can be either next to the exe, or in %USERPROFILE%, unix-style.

That mostly leaves a shortcut from the start menu and/or desktop, which I agree would be a nice addition. There is some discussion about this on the WinGet side of things, but I'm not holding my breath. We could generate one on first app start, or have a menu item in the tray icon.

Are there other specific reasons you think a proper installer is necessary?

**Comment by flyingpie** [comment]
Current versions of WTQ 2 are now installable through:

```
winget install windows-terminal-quake
```
