### ISSUE TITLE
Feature Request: display badge in taskbar

### ISSUE THREAD

**Issue by PiAlma** [flyingpie/windows-terminal-quake#125]
I would like to use wtq ([v2.0.0-prerelease6](https://github.com/flyingpie/windows-terminal-quake/releases/tag/v2.0.0-pre6)) with teams, but when the window is controlled by wtq, the badge disappears from the taskbar. So I am unable to see if there are pending messages.

No wtq → with badge 
![image](https://github.com/flyingpie/windows-terminal-quake/assets/152856817/2b470894-5246-43f9-b0f6-459723dff2e9)

With wtq → no badge
![image](https://github.com/flyingpie/windows-terminal-quake/assets/152856817/9deed69c-24e8-43d6-b228-111c3d833d04)

Could you add an option to display the badges in taskbar for windows controlled by wtq?

**Comment by flyingpie** [comment]
Hey @PiAlma Thank you for reporting this!

This seems like some sort of bug.

What does the badge actually mean?

**Comment by PiAlma** [comment]
The badge turn red when I have unread messages (teams is a messaging app).

**Comment by flyingpie** [comment]
@PiAlma I've uploaded a release that contains support for the "TaskBarIconVisibility"-option.

Could you set that to "AlwaysVisible", and see if the problem persists?

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v2.0.0-pre7

**Comment by flyingpie** [comment]
Note to self: my guess at this point is that this is due to WTQ setting window style flags, usually meant to show/hide the taskbar icon/button.

The "badges"-style functionality is likely handled through the same path, and we presumably strip it off during the icon visibility toggle.

Here's the win32 function we use to toggle visibility:
http://winapi.freetechsecrets.com/win32/WIN32SetWindowLong.htm
Specifically, we're the "GWL_EXSTYLE" flag.

The pre7 release adds the ability to disable this behavior altogether, which I'm hoping is gonna confirm or deny whether this part of the app is indeed the culprit.

**Comment by PiAlma** [comment]
It works !
Thank you.
