### ISSUE TITLE
McAfee deleted this tool

### ISSUE THREAD

**Issue by programus** [flyingpie/windows-terminal-quake#40]
I extract the file from the zip I downloaded from the release page. While I run it for a while, the exe file is deleted by McAfee since it consider it as a virus. 

![image](https://user-images.githubusercontent.com/956125/98464252-f9238400-2204-11eb-9039-d60d6a1b9f99.png)

Which one is bad? The tool or the McAfee?

**Comment by flyingpie** [comment]
Hey @programus! Thank you for posting this issue. It's a thing that more people have encountered, with different scanners.

The problem seems to relate to a couple things:
- The app is not signed
- The app is fairly niche, meaning that most virus scanners have not seen it before
- The app uses some hacky ways of accomplishing its features, that are apparently often found in malware. Controlling an entirely different process (wt.exe) being one of them.

I don't have any plans to mitigate this, since it's just a bunch of false positives. If you worry about the binaries that are under the "Releases"-tabs, you can take a look at the code yourself and run a build using build.ps1. As long as VS2019 is installed, it should spit out a similar exe.

**Comment by programus** [comment]
@flyingpie Thank you for your reponse. I have uninstalled the annoying McAfee.
