### ISSUE TITLE
Cannot bind to ` key

### ISSUE THREAD

**Issue by Gerboa** [flyingpie/windows-terminal-quake#60]
The button in the top-left of my keyboard enters a \` (backtick) normally and ¬ shifted.

I've tried entering \` as the key to bind to (plus Control) but it doesn't work. ^Q and ^' work (' being OemTilde).

**Comment by flyingpie** [comment]
@Gerboa Hey! Thanks for reporting the issue. I wonder if this is caused by a different keyboard layout, can you tell me which one you're using?

**Comment by Deus-Rex** [comment]
It's the UK layout. I have the same thing.

**Comment by flyingpie** [comment]
@Deus-Rex Thank you for mentioning this, I was able to reproduce the issue.

It turns out that that specific keyboard language doesn't emit "Oemtilde" from the backtick-key, but a "negation" sign, which surfaces as key code "Oem8".

This setup worked for me, using the UK keyboard layout:

```json
{
	"HotKeys": [
		{ "Modifiers": "Control", "Key": "Oem8" }
	]
}
```

@Gerboa @Deus-Rex Could you please take a look and try this on your machines?

**Comment by Deus-Rex** [comment]
That did the trick., works perfect. Thanks mate.
