### ISSUE TITLE
Accssesibility by ALT+TAB

### ISSUE THREAD

**Issue by metya** [flyingpie/windows-terminal-quake#73]
Hello! 
Great tool!

But It would be great if the terminal under the tool could be accessible by Alt + Tab shortcut like any other window in the workspace.
By the options in setting for example.

Thank you!)

**Comment by flyingpie** [comment]
@metya Thank you for your feedback!

Just to confirm, the point is that you don't want the terminal to disappear from the taskbar?

**Comment by metya** [comment]
So if the window is disappeared from the taskbar that means this window is no more accessible by Alt+Tab?

Hmm. If so, maybe anyway a good option to have the terminal on the taskbar, why not.


But I wanted just able to switch to the terminal which is in the down position, cause now the terminal doesn't disappear if lost focus, but if I switch to fullscreen IDE, for example, I lose the terminal, but it is still in the down position, and if I want to switch to it, I need push ctrl+~ twice - first to up the terminal and second to down it again to make it visible again.

So it a little bit inconvenient. That I wanted to try to say)

**Comment by flyingpie** [comment]
@metya Thank you for explaining this further, I actually noticed that it might be inconvenient that taskbar icon visibility and alt-tab presence seem to be linked.

However, since you brought up the "hidden behind another app"-thing, there is a setting that auto-hides the terminal if focus is lost, would that solve the problem perhaps?

https://flyingpie.github.io/windows-terminal-quake/settings/hide-on-focus-lost/

**Comment by metya** [comment]
No, I don't want to hide the terminal when it lost focus. Cause If I switch in a window that just not in fullscreen mode, I can anyway touch my terminal by mouse and return focus - it is convenient. Or switch my mouse to another monitor and have the terminal on screen.

Oh, and I noticed that you have the documentation! That's good because I didn't understand how some options are work :) Thank you for this)

**Comment by flyingpie** [comment]
Not sure if there's a way to hide the app from the taskbar, but not from the alt-tab menu.

If we had a setting that kept the icon visible on the taskbar, would that solve your use case? It would still be invisible when the terminal is toggled off, mind you.

![linus](https://user-images.githubusercontent.com/1295673/116424049-7f7a6380-a841-11eb-84dd-b506fba49d4f.gif)

**Comment by metya** [comment]
I think It's ok if there will an icon on the taskbar. For me, it's not a big deal!

Thank you very much for your work.

**Comment by flyingpie** [comment]
@metya Thank you for the feedback, I'll include this in the next release, today or tomorrow :)

**Comment by flyingpie** [comment]
@metya New release is available here (make sure to choose the latest, I've kept multiple since I'm changing a ton of stuff, some of which may break between previews:

https://github.com/flyingpie/windows-terminal-quake/releases/tag/v1.2.0

The setting itself (docs haven't been updated yet):

```json
{
	"TaskBarIconVisibility": "WhenTerminalVisible"
}
```

Possible values are:
- "AlwaysHidden" (default)
- "AlwaysVisible"
- "WhenTerminalVisible" (the reason for the change)

Please let me know what you think!

**Comment by metya** [comment]
Just tested it! Everything works! It's great! 
But that thing when the terminal is going up and then minimizing animation happens) A little bit annoying, but it's ok! 

Thank you!)

**Comment by flyingpie** [comment]
@metya You're welcome, thank you for adding to the conversation!

What do you mean by the minimizing animation? Can you show me your settings file?

**Comment by metya** [comment]
I mean when I push ctrl+~ to up the terminal, after up animation there is animation like I minimizing window on the taskbar.

do you see that on my screen record?)
![minimizing_animation2](https://user-images.githubusercontent.com/968934/116784461-f8292c00-aa9c-11eb-817a-c67f6262b0c9.gif)

**Comment by flyingpie** [comment]
@metya Huh, that's something alright. I actually have the animations turnt off, so didn't notice this initially. Perhaps it would be doable to move the entire window to somewhere else before minimizing, so you wouldn't see the animation.

Thank you for letting me know :)
